#!/usr/bin/env bash
# show me the domain

show_me_ip ()
{
    echo -n "The subdomain $1 is a "
    dig "$1.$2" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
    echo -n " record and points to "
    dig "$1.$2" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
    echo ""
}

if [ $# -gt 1 ]; then
    show_me_ip "$2" "$1"
else
    for sub in "www" "lb-01" "web-01" "web-02"
        do  show_me_ip "$sub" "$1" 
    done
fi

