#!/usr/bin/env bash
# install nginx and run it script

# Update package lists and install Nginx
apt update && apt install -y nginx

if [[ ! -d /var/www/html ]]; then
    mkdir -p /var/www/html
fi
echo "Hello World!" > /var/www/html/index.html
# Write the server configuration to the file
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    location /redirect_me {
        rewrite ^ / permanent;
    }
}
" > /etc/nginx/sites-available/default
new_string = "index.nginx-debian.html;
    location /redirect_me {
        rewrite ^ / permanent;
    }
"
sed -i "s/index.nginx-debian.html;/$new_string/" /etc/nginx/sites-available/default
# Restart Nginx
service nginx restart
