#!/usr/bin/env bash
# install nginx and run it script
# shellcheck disable=SC2154 

# Update package lists and install Nginx
apt update && apt install -y nginx


NEW_STRING="\\\tadd_header X-Served-By $HOSTNAME;\n"
sed -i "34i $NEW_STRING" /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
