#!/usr/bin/env bash
# shellcheck disable=SC2154 
# install nginx and run it script

# Update package lists and install Nginx
apt update && apt install -y nginx


NEW_STRING="\\\tadd_header X-Served-By $HOSTNAME;\n"
sudo sed -i "37i $NEW_STRING" /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
