#!/usr/bin/env bash
#Display all processes data


start() {
    bash ./manage_my_process &
    echo $! >| /var/run/my_process.pid
    echo manage_my_process started
}
stop() {
    pkill -f "./manage_my_process"
    rm /var/run/my_process.pid
    echo manage_my_process stopped
}
restart(){
    pkill -f "./manage_my_process"
    rm /var/run/my_process.pid
    bash ./manage_my_process &
    echo $! >| /var/run/my_process.pid
    echo manage_my_process restarted
}

if [[ $1 == "start" ]]; then
    start
elif [[ $1 == "stop" ]]; then
    stop
elif [[ $1 == "restart" ]]; then
    restart
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi