#!/usr/bin/env bash
#Display all processes data
trap 'echo "I hate the kill command"; exit;' SIGTERM
trap 'exit;' SIGQUIT 
trap 'echo Y U no love me?!' SIGINT
while true
do
    echo I am alive! >> /tmp/my_process;
    sleep 2;
done
