#!/usr/bin/env bash
#print "Best School" 10 times using while and say hi in 9
while read -r line; do
  username=$(echo "$line" | cut -d ":" -f 1)
  gang=$(echo "$line" | cut -d ":" -f 4)
  home=$(echo "$line" | cut -d ":" -f 6)
  shell=$(echo "$line" | cut -d ":" -f 7)
  user=$(echo "$line" | cut -d ":" -f 3)
  pass=$(echo "$line" | cut -d ":" -f 2)
  info=$(echo "$line" | cut -d ":" -f 5)


  echo "$username"
  echo "The user $username is part of the $gang gang, lives in $home and rides $shell. $user's place is protected by the passcode $pass, more info about the user here: $info"
done < /etc/passwd
