#!/usr/bin/env bash
#print "Best School" 10 times using while and say hi in 9
i=0;
while  [ $i -lt 10 ]
do
    if (($i == 9))
    then
        echo "Hi";
    fi
    echo "Best School";
    ((i++))
done;
