#!/usr/bin/env bash
#print "Best School" 10 times using while and say hi in 9
h=0;
while [ $h -lt 13 ]
do
    echo "Hour: $h";
    m=1;
    while [ $m -lt 60 ]
    do
        echo $m;
        ((m++))
    done
    ((h++))
done;
