#!/usr/bin/env bash
# Add text to html file
sudo su
if [[ ! -d /var/www/html ]]; then
    mkdir -p /var/www/html
fi
echo "Hello Holberton" > /var/www/html/index.html
echo "ServerName localhost" >> /etc/apache2.conf
service apache2 restart
