#!/usr/bin/env bash
# Changes nginx config the same
sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
chmod 604 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
